# Defines a default set of lint rules enforced for projects at Google. For
# details and rationale, see https://github.com/dart-lang/pedantic.
include: package:pedantic/analysis_options.yaml
linter:
  rules:
    - always_declare_return_types
    - annotate_overrides
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - comment_references
    - constant_identifier_names
    - empty_catches
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - non_constant_identifier_names
    - only_throw_errors
    - overridden_fields
    - parameter_assignments
    - prefer_final_fields
    - prefer_final_locals
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
