name: path_to_regexp_demo
description: A path_to_regexp demo for testing routes.
author: Leon Senft <leonsenft@google.com>
homepage: https://github.com/leonsenft/path_to_regexp_demo

environment:
  sdk: ">=2.0.0-dev.66.0 <2.0.0"

dependencies:
  angular: 5.0.0-beta
  angular_components: 0.9.0-beta
  path_to_regexp: ^0.1.0

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
  sass_builder: ^2.1.0
