name: path_to_regexp_demo
description: A path_to_regexp demo for testing routes.
author: Leon Senft <leonsenft@google.com>
homepage: https://github.com/leonsenft/path_to_regexp_demo

environment:
  sdk: ^2.0.0

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  path_to_regexp: ^0.1.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.1
  build_test: ^0.10.3
  build_web_compilers: ^0.4.3
  pageloader: ^3.0.0
  sass_builder: ^2.1.0
  test: ^1.3.0
