name: path_to_regexp_demo
description: A path_to_regexp demo for testing routes.
author: Leon Senft <leonsenft@google.com>
homepage: https://github.com/leonsenft/path_to_regexp_demo

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  angular: ^5.2.0
  angular_components: ^0.12.0
  path_to_regexp: ^0.2.1

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.2.0
  build_test: ^0.10.0
  build_web_compilers: ^1.1.0
  pageloader: ^3.1.0
  sass_builder: ^2.1.0
  test: ^1.3.0
