name: path_to_regexp_demo
description: A path_to_regexp demo for testing routes.
author: Leon Senft <leonsenft@google.com>
homepage: https://github.com/leonsenft/path_to_regexp_demo

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  angular: 6.0.0-alpha+1
  angular_components: 0.14.0-alpha+1
  path_to_regexp: ^0.2.1

dev_dependencies:
  angular_test: 2.4.0
  build_runner: 1.7.1
  build_test: 0.10.9+1
  build_web_compilers: 2.7.1
  pageloader: 3.2.2
  pedantic: 1.8.0
  sass_builder: 2.1.3
  test: 1.9.4
